[Eth]
NetworkId = 15003
SyncMode = "full"
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
NoPruning = true
NoPrefetch = false
TxLookupLimit = 2350000
TransactionHistory = 2350000
StateScheme = "hash"
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 64
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 0e+00

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 10000000000
Recommit = 999999999000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 10000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 3600000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 1
PriceBump = 100

[Eth.GPO]
Blocks = 120
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 2

[Node]
DataDir = ""
IPCPath = "geth.ipc"
HTTPHost = ""
HTTPModules = []
WSHost = ""
WSModules = []
AllowUnprotectedTxs = true

[Node.P2P]
MaxPeers = 100
NoDiscovery = true
StaticNodes = [
	"enode://56724a169266dedfbb41dc50a1f237f4b55569fadccce347c2bb25526c1357b6ff9450ce91c0f21a13abb02fa348ad9e928e8a4fee969a1f14a943c8f6409fb1@127.0.0.1:30300",
]
TrustedNodes = [
	"enode://56724a169266dedfbb41dc50a1f237f4b55569fadccce347c2bb25526c1357b6ff9450ce91c0f21a13abb02fa348ad9e928e8a4fee969a1f14a943c8f6409fb1@127.0.0.1:30300",
]
ListenAddr = ""
DiscAddr = ""
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 0
ReadHeaderTimeout = 0
WriteTimeout = 0
IdleTimeout = 0
