---
name: Docker Build + Push

inputs:
  github-token:
    required: true
  tags:
    required: false
    type: string
    description: "Comma separated list of Docker tags (e.g. ghcr.io/immutable/immutable-geth/immutable-geth:latest)"
  dockerfile:
    required: false
    type: string
    default: "Dockerfile"
  build-args:
    required: false
    type: string

outputs:
  digest:
    description: "The digest of the built image"
    value: ${{ steps.build.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # pin@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # pin@v5.7.0
      with:
        images: ghcr.io/${{ github.repository }}/s
        github-token: ${{ inputs.github-token }}

    - name: Restore Go mod (pkg)
      uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # pin@v4.2.2
      with:
        path: "~/go/pkg/mod"
        key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}-${{ github.sha }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}-${{ github.sha }}-
          ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-gomod-

    - name: Restore Go build (test)
      uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # pin@v4.2.2
      with:
        path: "~/.cache/go-build"
        key: ${{ runner.os }}-gobuild-${{ hashFiles('**/go.sum') }}-${{ github.sha }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-gobuild-${{ hashFiles('**/go.sum') }}-${{ github.sha }}-
          ${{ runner.os }}-gobuild-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-gobuild-

    - name: Set up Docker Context for buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # pin@v3.10.0
      with:
        version: latest
        endpoint: builders

    - name: Build and push
      id: build
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # pin@v6.15.0
      with:
        context: .
        platforms: linux/amd64
        file: ${{ inputs.dockerfile }}
        push: true
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/immutable-geth:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/immutable-geth:cache,mode=max
        provenance: true
