---
name: "Test chain rewind"

runs:
  using: composite
  steps:
    - name: Setup
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # pin@v5.3.0
      with:
        go-version: 1.20.x

    - name: Build
      shell: bash
      run: |
        make geth

    - name: Test
      shell: bash
      run: ./.github/scripts/rewind_test.sh
