---
name: "Test E2E against live network"

inputs:
  rpc:
    description: RPC URL
  priv_key:
    description: hex encoded private key with funds on the env
runs:
  using: composite
  steps:
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Deps
      shell: bash
      run: |
        go get ./tests/immutable/...

    - name: Tests
      shell: bash
      env:
        PRIV_KEY: ${{ inputs.priv_key }}
      run: ./.github/scripts/e2e.sh ${{ inputs.rpc }}
