name: Build docker image, tag and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-20-04-4-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/push
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
