name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tags
        shell: bash
        run: |
          REPOSITORY_NAME="$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
          BUILD_TIMESTAMP="$(date +%s)"
          SHORT_SHA="$(git rev-parse --short HEAD)"
          echo TAGS="ghcr.io/${{ github.repository }}/immutable-geth:develop-$BUILD_TIMESTAMP-git.$SHORT_SHA" >> $GITHUB_ENV

      - uses: ./.github/actions/push
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ env.TAGS }}
