name: Build docker image, tag and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: # see this: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-20-04-4-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/push
        with:
          environment: dev
          dockerfile: "Dockerfile"
          go-mod-cache-path: "~/go/pkg/mod"
          go-build-cache-path: "~/.cache/go-build"

  tests:
    name: Tests
    runs-on: ubuntu-20-04-4-cores
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Cache modules
        uses: ./.github/actions/cache/golang
      - name: All Tests
        shell: bash
        run: |
          go run build/ci.go install
          go test $(go list ./... | grep -v 'go-ethereum/tests/immutable') -p 1 --parallel 4 -timeout=30m
