name: Release

on:
  release:
    types: [published]

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Set Release Tag
        run: echo "TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/push
        id: push
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: "ghcr.io/${{ github.repository }}/immutable-geth:latest,ghcr.io/${{ github.repository }}/immutable-geth:${{ env.TAG }}"
      
      - name: Attest
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}/immutable-geth
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false
