name: Release

on:
  release:
    types: [published]

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Set Release Tag
        run: echo "TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/push
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: "ghcr.io/${{ github.repository }}/immutable-geth:latest,ghcr.io/${{ github.repository }}/immutable-geth:${{ env.TAG }}"
