name: Tag

on:
  push:
    tags:
      - "**"

jobs:
  push:
    name: Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Release Tag
        run: echo "TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/push
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: "ghcr.io/immutable/immutable-geth:${{ env.TAG }}"
